services:
    - type: web
    name: saqr-alfalah
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
            - key: TELEGRAM_TOKEN
        value:         value: 8012345678:AAFkdjsaFJDKL_ASdj1239fkl
            - key: CHAT_ID
        value:         value: 987654321
